//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBKHACHSAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PHONG()
        {
            this.HINHANHPHONGs = new HashSet<HINHANHPHONG>();
            this.THIETBIPHONGs = new HashSet<THIETBIPHONG>();
        }
    
        public int IDPHONG { get; set; }
        public Nullable<int> SOPHONG { get; set; }
        public string TENPHONG { get; set; }
        public string MOTAPHONG { get; set; }
        public Nullable<decimal> GIAPHONG { get; set; }
        public Nullable<int> SOLUONGGIUONGPHONG { get; set; }
        public Nullable<int> SOLUONGPHONGTAM { get; set; }
        public string TENDANGNHAP { get; set; }
        public Nullable<decimal> DELAYPHONG { get; set; }
        public Nullable<int> IDLOAIPHONG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HINHANHPHONG> HINHANHPHONGs { get; set; }
        public virtual LOAIPHONG LOAIPHONG { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THIETBIPHONG> THIETBIPHONGs { get; set; }
    }
}
