//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBKHACHSAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGTINKHACHHANG
    {
        public int IDTHONGTINKHACHHANG { get; set; }
        public string TEN { get; set; }
        public string EMAIL { get; set; }
        public string TENDANGNHAP { get; set; }
    
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
