
---------------------------------------------------CREATE TABLE---------------------------------------------------
CREATE TABLE LOAITAIKHOAN(IDLOAITAIKHOAN INT IDENTITY PRIMARY KEY, TENLOAITAIKHOAN NVARCHAR(100))
GO
CREATE TABLE TAIKHOAN(TENDANGNHAP VARCHAR(200) PRIMARY KEY, MATKHAU VARCHAR(200), TRANGTHAI INT, IDLOAITAIKHOAN INT FOREIGN KEY (IDLOAITAIKHOAN) REFERENCES LOAITAIKHOAN (IDLOAITAIKHOAN))
GO
CREATE TABLE LOAIPHONG(IDLOAIPHONG INT IDENTITY PRIMARY KEY, TENLOAIPHONG NVARCHAR(200))
GO
CREATE TABLE PHONG(IDPHONG INT IDENTITY PRIMARY KEY, SOPHONG INT UNIQUE, TENPHONG NVARCHAR(200), MOTAPHONG NVARCHAR(200), GIAPHONG DECIMAL(18,0), SOLUONGGIUONGPHONG INT, SOLUONGPHONGTAM INT, TENDANGNHAP VARCHAR(200) FOREIGN KEY (TENDANGNHAP) REFERENCES TAIKHOAN(TENDANGNHAP), DELAYPHONG DECIMAL(3,1), IDLOAIPHONG INT FOREIGN KEY (IDLOAIPHONG) REFERENCES LOAIPHONG(IDLOAIPHONG))
GO
CREATE TABLE HINHANHPHONG(IDHINHANHPHONG INT IDENTITY PRIMARY KEY, TENHINHANHPHONG NVARCHAR(200), IDPHONG INT FOREIGN KEY (IDPHONG) REFERENCES PHONG(IDPHONG), VITRI INT)
GO
---------------------------------------------------INESRT TABLE---------------------------------------------------
INSERT LOAITAIKHOAN (TENLOAITAIKHOAN) 
VALUES
(N'QUẢN TRỊ VIÊN'),
(N'NHÂN VIÊN'),
(N'KHÁCH HÀNG')
GO
INSERT TAIKHOAN (TENDANGNHAP, MATKHAU, TRANGTHAI, IDLOAITAIKHOAN) 
VALUES 
('ADMIN', 123, 1, 1),
('NHANVIENA', 123, 1, 2),
('KHACHHANGA', 123, 1, 3)
GO
INSERT LOAIPHONG(TENLOAIPHONG) 
VALUES
(N'Phòng Couple'),
(N'Phòng Family'),
(N'Phòng VIP Family');
GO
--INSERT INTO PHONG (SOPHONG, TENPHONG, MOTAPHONG, GIAPHONG, SOLUONGGIUONGPHONG, SOLUONGPHONGTAM, TENDANGNHAP, DELAYPHONG, IDLOAIPHONG)
--VALUES
--(101, N'Phòng Family', N'Phòng rộng rãi, gia đình', 1000000, 2, 1, 'admin', 0.1, 1),
--(201, N'Phòng Deluxe', N'Phòng rộng rãi, đầy đủ tiện nghi', 1200000, 2, 1, 'admin', 0.2, 2),
--(202, N'Phòng Standard', N'Phòng tiêu chuẩn, tiện lợi', 800000, 1, 1, 'admin', 0.3, 2),
--(301, N'Phòng VIP', N'Phòng sang trọng với tầm nhìn đẹp', 3000000, 3, 1, 'admin', 0.4, 3),
--(302, N'Phòng Superior', N'Phòng hiện đại với nội thất cao cấp', 1500000, 2, 1, 'admin', 0.5, 3),
--(304, N'Phòng Executive', N'Phòng có không gian làm việc tiện nghi', 1800000, 2, 1, 'admin', 0.6, 3),
--(305, N'Phòng Suite', N'Phòng cao cấp với phòng khách riêng', 2500000, 3, 1, 'admin', 0.7, 3),
--(203, N'Phòng Premier', N'Phòng rộng rãi, trang bị tiện nghi sang trọng', 2000000, 2, 1, 'admin', 0.8, 2),
--(204, N'Phòng Twin', N'Phòng có 2 giường đơn phù hợp nhóm bạn', 900000, 2, 1, 'admin', 0.9, 2),
--(102, N'Phòng Single', N'Phòng đơn dành cho khách du lịch một mình', 700000, 1, 1, 'admin', 0.10, 1);
--GO
--INSERT INTO HINHANHPHONG (TENHINHANHPHONG, IDPHONG, VITRI)
--SELECT 
--    CONCAT(N'room-1', '.jpg') AS TENHINHANHPHONG,  -- Tạo tên ảnh theo TENPHONG
--    IDPHONG,
--	1
--FROM PHONG;
--GO
---------------------------------------------------CREATE PROC---------------------------------------------------
CREATE PROC DANGNHAP(@TENDANGNHAP VARCHAR(200), @MATKHAU VARCHAR(200)) AS
BEGIN
	IF EXISTS (SELECT * FROM TAIKHOAN WHERE TENDANGNHAP = @TENDANGNHAP AND MATKHAU = @MATKHAU AND TRANGTHAI = 1) BEGIN
		SELECT * FROM TAIKHOAN WHERE TENDANGNHAP = @TENDANGNHAP AND MATKHAU = @MATKHAU
	END 
END
GO
CREATE PROC DANGKY(@TENDANGNHAP VARCHAR(200), @MATKHAU VARCHAR(200)) AS
BEGIN
	IF NOT EXISTS (SELECT * FROM TAIKHOAN WHERE TENDANGNHAP = @TENDANGNHAP) BEGIN
		INSERT TAIKHOAN (TENDANGNHAP, MATKHAU, TRANGTHAI, IDLOAITAIKHOAN) VALUES (@TENDANGNHAP, @MATKHAU, 1, 3)
		SELECT * FROM TAIKHOAN WHERE TENDANGNHAP = @TENDANGNHAP AND MATKHAU = @MATKHAU
	END
END
GO
CREATE PROC THEMTAIKHOAN(@TENDANGNHAP VARCHAR(200), @MATKHAU VARCHAR(200), @TRANGTHAI INT, @IDLOAITAIKHOAN INT) AS
BEGIN
	IF NOT EXISTS (SELECT * FROM TAIKHOAN WHERE TENDANGNHAP = @TENDANGNHAP) BEGIN
		INSERT TAIKHOAN (TENDANGNHAP, MATKHAU, TRANGTHAI, IDLOAITAIKHOAN) VALUES (@TENDANGNHAP, @MATKHAU, @TRANGTHAI, @IDLOAITAIKHOAN)
		SELECT * FROM TAIKHOAN WHERE TENDANGNHAP = @TENDANGNHAP AND MATKHAU = @MATKHAU
	END
END
GO
CREATE PROC THEMPHONG(@SOPHONG INT, @TENPHONG NVARCHAR(200), @MOTAPHONG NVARCHAR(200), @GIAPHONG DECIMAL(18,0), @SOLUONGGIOUNGPHONG INT, @SOLUONGPHONGTAM INT, @TENDDANGNHAP VARCHAR(200), @IDLOAIPHONG INT, @TENHINHANHPHONG NVARCHAR(200)) AS
BEGIN
	IF NOT EXISTS (SELECT * FROM PHONG WHERE SOPHONG = @SOPHONG) BEGIN

		DECLARE @DELAYPHONG DECIMAL(3,2)
		SELECT TOP 1 @DELAYPHONG = (DELAYPHONG + 0.1) FROM PHONG ORDER BY DELAYPHONG DESC

		INSERT PHONG (SOPHONG, TENPHONG, MOTAPHONG, GIAPHONG, SOLUONGGIUONGPHONG, SOLUONGPHONGTAM, TENDANGNHAP, IDLOAIPHONG, DELAYPHONG) VALUES (@SOPHONG, @TENPHONG, @MOTAPHONG, @GIAPHONG, @SOLUONGGIOUNGPHONG, @SOLUONGPHONGTAM, @TENDDANGNHAP, @IDLOAIPHONG, @DELAYPHONG)

		DECLARE @IDPHONG INT
		SELECT @IDPHONG = IDPHONG FROM PHONG WHERE SOPHONG = @SOPHONG

		INSERT HINHANHPHONG (TENHINHANHPHONG, IDPHONG, VITRI) VALUES (@TENHINHANHPHONG, @IDPHONG, 1)

		SELECT P.* FROM PHONG AS P, HINHANHPHONG AS HAP WHERE P.IDPHONG = HAP.IDPHONG AND P.IDPHONG = @IDPHONG

	END
END
GO 
CREATE PROC XOAPHONG(@IDPHONG INT) AS
BEGIN
	IF EXISTS (SELECT * FROM PHONG WHERE IDPHONG = @IDPHONG) BEGIN
		DELETE HINHANHPHONG WHERE IDPHONG = @IDPHONG
		
		DELETE PHONG WHERE IDPHONG = @IDPHONG

		IF NOT EXISTS (SELECT * FROM PHONG WHERE IDPHONG = @IDPHONG) BEGIN
			SELECT TOP 1 * FROM PHONG
		END

	END
END
GO 
CREATE PROC CAPNHATPHONG(@IDPHONG INT, @TENHINHANHPHONG NVARCHAR(200), @SOPHONG INT, @TENPHONG NVARCHAR(200), @MOTAPHONG NVARCHAR(200), @GIAPHONG DECIMAL(18,0), @SOLUONGGIUONGPHONG INT, @SOLUONGPHONGTAM INT, @IDLOAIPHONG INT) AS
BEGIN
	IF EXISTS (SELECT * FROM PHONG AS P, HINHANHPHONG AS HAP, LOAIPHONG AS LP WHERE P.IDPHONG = @IDPHONG AND P.IDPHONG = HAP.IDPHONG AND LP.IDLOAIPHONG = P.IDLOAIPHONG) BEGIN
		UPDATE PHONG SET SOPHONG = @SOPHONG, TENPHONG = @TENPHONG, MOTAPHONG = @MOTAPHONG, GIAPHONG = @GIAPHONG, SOLUONGGIUONGPHONG = @SOLUONGGIUONGPHONG, @SOLUONGPHONGTAM = @SOLUONGPHONGTAM, IDLOAIPHONG = @IDLOAIPHONG WHERE IDPHONG = @IDPHONG
		UPDATE HINHANHPHONG SET TENHINHANHPHONG = @TENHINHANHPHONG WHERE IDPHONG = @IDPHONG

		SELECT P.* FROM PHONG AS P, HINHANHPHONG AS HAP, LOAIPHONG AS LP WHERE P.IDPHONG = @IDPHONG AND P.IDPHONG = HAP.IDPHONG AND LP.IDLOAIPHONG = P.IDLOAIPHONG

	END
END